services:
  db:
    image: postgres:16.4
    restart: always
    container_name: spring-postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: spring
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "spring-rabbitmq"
    environment:
      - 'RABBITMQ_DEFAULT_PASS=string'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  springdata:
